Add azure-pipelines functionality
statisticsnorway/sagalog-postgres pull request #1
Opened 2020-08-25 07:49 UTC by SjurSutterudSagen

2020-08-25 08:19 UTC, takvamborgen requested changes
You need to add a postgres container for integration tests. See the pipelines template for full maven build including integration tests.

2020-08-28 11:36 UTC, InsulaVentus commented on azure-pipelines.yml
> +    container: ${{ parameters.mavenContainer }}
As this is a jdk11 app it shouldn't be necessary to run this job inside a container. Also, as we're running the tests inside this container and the postgres database inside another we cannot connect from test to database using `localhost` causing tests to fail.

2020-08-28 13:50 UTC, SjurSutterudSagen commented on azure-pipelines.yml
> +    container: ${{ parameters.mavenContainer }}
Implemented, and it fixed the problem.

2020-09-02 07:04 UTC, InsulaVentus approved these changes

2020-09-02 07:04 UTC, InsulaVentus commented on pom.xml
> +                    <plugin>
Could be worth to try and remove `maven-surefire-plugin` from the coverage profile (if you haven't tried that already). Otherwise, if you have verified that the pipeline builds the expected artifacts and that the coverage report is generated correctly I think this PR is ok.

2020-09-02 10:27 UTC, SjurSutterudSagen commented on pom.xml
> +                    <plugin>
Removing `maven-surefire-plugin` worked, fix implemented.

2020-09-02 10:39 UTC, InsulaVentus approved these changes

2020-09-03 06:49 UTC, merged